//! Compact ISO 14819-2 event-code descriptions.
//!
//! The full event list is large and copyrighted as a separate standard; this
//! subset covers the codes most often seen on-air so decoded messages have a
//! human-readable `description`. Unknown codes still pass through numerically.

pub fn event_description(code: u16) -> Option<&'static str> {
    Some(match code {
        1 => "traffic problem",
        2 => "queuing traffic",
        101 => "stationary traffic",
        102 => "queuing traffic",
        103 => "slow traffic",
        104 => "heavy traffic",
        105 => "traffic flowing freely",
        106 => "long queues",
        107 => "traffic congestion",
        108 => "traffic earlier than normal",
        109 => "traffic later than normal",
        201 => "accident",
        202 => "serious accident",
        203 => "multi-vehicle accident",
        204 => "accident involving lorry",
        301 => "closure",
        302 => "blocked",
        303 => "blocked for heavy vehicles",
        401 => "carriageway reduced",
        501 => "closed",
        502 => "closed ahead",
        503 => "entry slip closed",
        504 => "exit slip closed",
        505 => "connecting carriageway closed",
        601 => "no motor vehicles",
        701 => "roadworks",
        702 => "major roadworks",
        703 => "resurfacing work",
        704 => "overhead powerworks",
        801 => "obstruction on the road",
        802 => "broken down vehicle",
        803 => "broken down lorry",
        804 => "vehicle on fire",
        901 => "flooding",
        902 => "danger of flooding",
        1101 => "snow on the road",
        1102 => "ice",
        1103 => "black ice",
        1104 => "freezing rain",
        1201 => "storm",
        1301 => "poor visibility",
        1307 => "fog",
        1401 => "high winds",
        1471 => "heavy snowfall",
        1481 => "blizzard",
        1501 => "delay",
        1601 => "police checkpoint",
        1681 => "security incident",
        1701 => "demonstration",
        1801 => "lane closed",
        1901 => "contraflow",
        2000 => "this message is cancelled",
        2047 => "alert-C system information",
        _ => return None,
    })
}
